json.extract! @me,
              :id,
              :first_name,
              :last_name,
              :gender,
              :email,
              :phone,
              :birthday,
              :image_url,
              :created_at,
              :updated_at
